data_augment:
- ALONG_AXIS_LIST:
  - x
  NAME: random_world_flip
- NAME: random_world_rotation
  WORLD_ROT_ANGLE:
  - -0.78539816
  - 0.78539816
- NAME: random_world_scaling
  WORLD_SCALE_RANGE:
  - 0.95
  - 1.05
fusion:
  args: []
  core_method: IntermediateFusionDataset
loss:
  args:
    cls_weight: 1.0
    reg: 2.0
  core_method: point_pillar_loss
lr_scheduler:
  core_method: cosineannealwarm
  epoches: 60
  lr_min: 2.0e-05
  warmup_epoches: 10
  warmup_lr: 0.0002
model:
  args:
    anchor_number: 2
    backbone_fix: false
    base_bev_backbone:
      layer_nums:
      - 3
      - 5
      - 8
      layer_strides:
      - 2
      - 2
      - 2
      num_filters:
      - 64
      - 128
      - 256
      num_upsample_filter:
      - 128
      - 128
      - 128
      upsample_strides:
      - 1
      - 2
      - 4
    compression: 32
    lidar_range: &id002
    - -102.4
    - -38.4
    - -5
    - 102.4
    - 38.4
    - 3
    max_cav: 2
    pillar_vfe:
      num_filters:
      - 64
      use_absolute_xyz: true
      use_norm: true
      with_distance: false
    point_pillar_scatter:
      grid_size: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 3
        - !!python/object/apply:numpy.dtype
          args:
          - i8
          - 0
          - 1
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          AAIAAAAAAADAAAAAAAAAAAEAAAAAAAAA
      num_features: 64
    shrink_header:
      dim:
      - 256
      input_dim: 384
      kernal_size:
      - 3
      padding:
      - 1
      stride:
      - 2
    v2vfusion:
      agg_operator: avg
      conv_gru:
        H: 48
        W: 128
        kernel_size:
        - - 3
          - 3
        num_layers: 1
      downsample_rate: 4
      gru_flag: true
      in_channels: 256
      num_iteration: 1
      use_temporal_encoding: true
      voxel_size: &id001
      - 0.4
      - 0.4
      - 8
    voxel_size: *id001
  core_method: point_pillar_v2vnet
name: point_pillar_v2vnet
optimizer:
  args:
    eps: 1.0e-10
    weight_decay: 0.0001
  core_method: Adam
  lr: 0.002
postprocess:
  anchor_args:
    D: 1
    H: 192
    W: 512
    cav_lidar_range: *id002
    feature_stride: 4
    h: 1.56
    l: 3.9
    num: 2
    r:
    - 0
    - 90
    vd: 8
    vh: 0.4
    vw: 0.4
    w: 1.6
  core_method: VoxelPostprocessor
  max_num: 100
  nms_thresh: 0.15
  order: hwl
  target_args:
    neg_threshold: 0.45
    pos_threshold: 0.6
    score_threshold: 0.2
preprocess:
  args:
    max_points_per_voxel: 32
    max_voxel_test: 70000
    max_voxel_train: 32000
    voxel_size: *id001
  cav_lidar_range: *id002
  core_method: SpVoxelPreprocessor
root_dir: '/media/jlutripper/Samsung_T51/V2Vreal/Retrain/t1'

train_params:
  batch_size: 4
  epoches: 65
  eval_freq: 1
  max_cav: 2
  save_freq: 1
# validate_dir: /media/jlutripper/Samsung_T51/V2Vreal/test/
validate_dir: '/media/jlutripper/Samsung_T51/V2Vreal/Retrain/augment_data'
# validate_dir: '/media/jlutripper/Samsung_T51/V2Vreal/augment_data'
# validate_dir: '/media/jlutripper/Samsung_T51/V2Vreal/Retrain/retrain/augment_data'
# validate_dir: '/media/jlutripper/Samsung_T51/V2Vreal/test_simple/test_01/'

wild_setting:
  async: false
  async_mode: sim
  async_overhead: 100
  backbone_delay: 10
  data_size: 1.06
  loc_err: false
  rot_x: 1.0
  rot_y: 0.0
  rot_z: 0.2
  ryp_std: 0.0
  seed: 20
  tran_x: 0.0
  tran_y: 0.0
  tran_z: 0.0
  transmission_speed: 27
  xyz_std: 0.0
yaml_parser: load_point_pillar_params
